import assert from "node:assert/strict";
import { selectReceiptArtifacts } from "./select-youtube-receipt-artifacts.mjs";
const ordinary = Array.from({ length: 51 }, (_, i) => ({ id: i + 1, name: `youtube-video-publish-apply-deck-${i}`, expired: false }));
const polyglot = Array.from({ length: 51 }, (_, i) => ({ id: i + 52, name: `youtube-polyglot-deck-${i}-apply`, expired: false }));
const metadata = Array.from({ length: 6 }, (_, i) => ({ id: i + 103, name: `metadata-${i}`, expired: false }));
const rows = [...ordinary.slice(4), ...polyglot, ...metadata.slice(0, 2), ...ordinary.slice(0, 4), ...metadata.slice(2)];
const pages = [{ total_count: 108, artifacts: rows.slice(0, 100) }, { total_count: 108, artifacts: rows.slice(100) }];
const selected = selectReceiptArtifacts(pages, { artifactCount: 102 });
assert.equal(selected.length, 102);
assert(ordinary.slice(0, 4).every(row => selected.some(item => item.id === row.id)));
assert.throws(() => selectReceiptArtifacts(pages.slice(0, 1), { artifactCount: 102 }), /Incomplete/);
assert.throws(() => selectReceiptArtifacts(pages, { artifactCount: 98 }), /count mismatch/);
const duplicate = structuredClone(pages); duplicate[1].artifacts[0] = duplicate[0].artifacts[0];
assert.throws(() => selectReceiptArtifacts(duplicate, { artifactCount: 102 }), /duplicate/);
const expired = structuredClone(pages); expired[0].artifacts[0].expired = true;
assert.throws(() => selectReceiptArtifacts(expired, { artifactCount: 102 }), /expired/);
const unsafe = structuredClone(pages); unsafe[0].artifacts[0].name = "youtube-video-publish-apply-../escape";
assert.throws(() => selectReceiptArtifacts(unsafe, { artifactCount: 102 }), /Unsafe/);
const drift = structuredClone(pages); drift[1].total_count = 109;
assert.throws(() => selectReceiptArtifacts(drift, { artifactCount: 102 }), /drift/);
console.log("complete receipt artifact pagination tests passed");
