import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { prepareReadyMedia, readyMediaPath, readyMediaSha256, verifyReadyMediaScope } from "./lib/youtube-ready-media.mjs";
const root = fs.mkdtempSync(path.join(os.tmpdir(), "ready-media-test-"));
const metadataPath = "outputs/video-generator/test/youtube_metadata.json";
const videoPath = "outputs/video-generator/test/lesson_es_lv.mp4";
const artifactName = "source-artifact";
fs.mkdirSync(path.join(root, artifactName, "outputs/video-generator/test"), { recursive: true });
const assignment = { assignmentKey: "ordinary|deck|LV|ES", videoType: "ordinary", setId: "deck", supportLang: "LV", targetLang: "ES", channelKey: "lv", youtubeChannelId: "channel", status: "claimed", publishAt: "2099-01-01T12:00:00Z", productionReadiness: { voiceId: "edge_lv-LV-EveritaNeural" }, thumbnail: { mode: "first_frame_auto" }, playlist: { ready: true, state: "resolved_existing", createAllowed: false, youtubePlaylistId: "playlist" } };
const metadata = { setId: "deck", supportLang: "LV", targetLang: "ES", title: "Approved title", description: "Approved description", campaignId: "source", campaignManifestHash: "source-hash", youtubePlaylistId: "playlist" };
fs.writeFileSync(path.join(root, artifactName, metadataPath), JSON.stringify(metadata));
fs.writeFileSync(path.join(root, artifactName, videoPath), "fixture-only");
const fingerprint = { sourceFingerprints: { offlineDeck: { sha256: "deck-sha" } } };
const campaign = { campaignId: "target", manifestHash: "target-hash", setId: "deck", status: "claimed", inputs: { partialRecoveryOfCampaignId: "source" }, evidence: fingerprint, assignments: [assignment] };
const source = { campaignId: "source", manifestHash: "source-hash", setId: "deck", evidence: fingerprint, assignments: [{ ...assignment, status: "superseded_partial_recovery", supersededByCampaignId: "target" }] };
const asset = { assignmentKey: assignment.assignmentKey, artifactId: 123, artifactName, metadataPath, videoPath, metadataSha256: readyMediaSha256(path.join(root, artifactName, metadataPath)), videoSha256: readyMediaSha256(path.join(root, artifactName, videoPath)), durationSeconds: 300 };
const spec = { schemaVersion: 1, sourceRunId: "123", sourceHeadSha: "a".repeat(40), sourceCampaignId: "source", sourceManifestHash: "source-hash", assets: [asset] };
verifyReadyMediaScope(spec, campaign, source);
const probe = { format: { duration: "300" }, streams: [{ codec_type: "audio" }, { codec_type: "video", width: 1280, height: 720 }] };
const prepared = prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset, probe });
assert.equal(prepared.title, metadata.title);
assert.equal(prepared.description, metadata.description);
assert.equal(prepared.campaignId, "target");
assert.equal(prepared.campaignManifestHash, "target-hash");
assert.equal(prepared.publishAt, assignment.publishAt);
assert.equal(prepared.privacyStatus, "private");
assert.equal(prepared.readyMediaSource.videoSha256, asset.videoSha256);
assert.throws(() => readyMediaPath(root, "../escape"), /Unsafe/);
const changed = structuredClone(campaign); changed.assignments[0].productionReadiness.voiceId = "other";
assert.throws(() => verifyReadyMediaScope(spec, changed, source), /voice changed/);
const wrongDeck = structuredClone(campaign); wrongDeck.evidence.sourceFingerprints.offlineDeck.sha256 = "changed";
assert.throws(() => verifyReadyMediaScope(spec, wrongDeck, source), /deck hash/);
const accepted = structuredClone(source); accepted.assignments[0].youtubeVideoId = "already-uploaded";
assert.throws(() => verifyReadyMediaScope(spec, campaign, accepted), /accepted/);
assert.throws(() => verifyReadyMediaScope({ ...spec, assets: [asset, asset] }, campaign, source), /scope count/);
assert.throws(() => prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset: { ...asset, videoSha256: "bad" }, probe }), /checksum/);
const wrongVideoPath = "outputs/video-generator/test/lesson_de_lv.mp4";
fs.writeFileSync(path.join(root, artifactName, wrongVideoPath), "fixture-only");
assert.throws(() => prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset: { ...asset, videoPath: wrongVideoPath }, probe }), /binding mismatch/);
assert.throws(() => prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset, probe: { ...probe, streams: [{ codec_type: "video", width: 1280, height: 720 }] } }), /streams/);
assert.throws(() => prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset, probe: { ...probe, streams: [{ codec_type: "audio" }, { codec_type: "video", width: 720, height: 1280 }] } }), /horizontal/);
assert.throws(() => prepareReadyMedia({ spec, campaign, source, artifactRoot: root, asset, probe, now: Date.parse(assignment.publishAt) }), /safely future/);
const polyAssignment = { ...assignment, assignmentKey: "polyglot|deck|LV|global_europe_core|hash|short_unverified", videoType: "polyglot", targetLang: "", targetLangs: ["EN", "ES", "FR", "DE"], targetLangsHash: "hash", bundleKey: "global_europe_core", contentScope: "short_unverified", maxDurationSeconds: 895 };
const polyMetadata = { ...metadata, videoType: "polyglot", targetLang: "", targetLangs: polyAssignment.targetLangs, targetLangsHash: "hash", bundleKey: "global_europe_core", contentScope: "short_unverified", videoPath: `/source/root/${videoPath}` };
fs.writeFileSync(path.join(root, artifactName, metadataPath), JSON.stringify(polyMetadata));
const polyAsset = { ...asset, assignmentKey: polyAssignment.assignmentKey, metadataSha256: readyMediaSha256(path.join(root, artifactName, metadataPath)), durationSeconds: 895 };
const polyCampaign = { ...campaign, assignments: [polyAssignment] };
assert.equal(prepareReadyMedia({ spec, campaign: polyCampaign, source, artifactRoot: root, asset: polyAsset, probe: { ...probe, format: { duration: "895" } } }).contentScope, "short_unverified");
assert.throws(() => prepareReadyMedia({ spec, campaign: polyCampaign, source, artifactRoot: root, asset: { ...polyAsset, durationSeconds: 895.1 }, probe: { ...probe, format: { duration: "895.1" } } }), /scope\/duration/);
assert.throws(() => prepareReadyMedia({ spec, campaign: { ...polyCampaign, assignments: [{ ...polyAssignment, contentScope: "full" }] }, source, artifactRoot: root, asset: polyAsset, probe: { ...probe, format: { duration: "895" } } }), /identity|scope\/duration/);
const parent = fs.readFileSync(".github/workflows/youtube-publication-campaign.yml", "utf8");
const worker = fs.readFileSync(".github/workflows/youtube-ready-media-route.yml", "utf8");
assert.match(parent, /inputs\.ready_media_spec == ''/);
assert.match(parent, /needs: \[preflight, routes, ready_media\]/);
assert.match(parent, /REUSE_APPROVED_READY_MEDIA/);
assert.match(worker, /gh api --paginate --slurp/);
assert.doesNotMatch(worker, /AI33_API_KEY|OPENAI_API_KEY|GENERATE_TTS_AUDIO|RENDER_POLYGLOT_VIDEO|build-deck-video|build-polyglot-video/);
assert.match(worker, /if: \$\{\{ always\(\) \}\}/);
console.log("ready media recovery tests passed");
